<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => 'dae2e31d635df5430139d5c99370f530bd55eced',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'dae2e31d635df5430139d5c99370f530bd55eced',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v5.2.27',
            'version' => '5.2.27.0',
            'reference' => 'dde1db116511aa4956389d75546c5be4c2beb2a6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'smarty/smarty' => array(
            'pretty_version' => 'v3.1.34',
            'version' => '3.1.34.0',
            'reference' => 'c9f0de05f41b9e52798b268ab1e625fac3b8578c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smarty/smarty',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
